version: 0.1.{build}
image: Visual Studio 2019

branches:
  only:
    - master

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build_script:
- dotnet build

test_script:
- OpenCover.Console.exe -register -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full GithubExplorer.IntegrationTests/GithubExplorer.IntegrationTests.csproj" -filter:"+[GithubExplorer*]* -[GithubExplorer.IntegrationTests*]*" -output:".\GithubExplorer_coverage.xml" -log:Verbose -oldstyle -returntargetcode
- codecov -f "GithubExplorer_coverage.xml"

artifacts:
  - path: "GithubExplorer_coverage.xml"